name: Test iOS

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    
    - name: build for iOS 9.0
      run: |
        cmake -E env CXXFLAGS="-fno-aligned-allocation" cmake -H. -Bbuild-ios -G Xcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=9.0 -DCMAKE_INSTALL_PREFIX=./build-ios/root -DCMAKE_IOS_INSTALL_COMBINED=YES -Dios_std_alternatives_TESTS_ENABLE_TESTS=On
        cmake --build build-ios --target install -j8

