name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    
    - name: build and run tests
      run: |
        cmake -H. -Bbuild -Dios_std_alternatives_TESTS_ENABLE_TESTS=On
        cmake --build build -j8
        ./build/tests/ios_std_alternatives_test
